"use client";
import { useEffect,useState } from "react";
import { ImagePlus,Loader2,Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
type CompanyForm={name:string;rnc:string;phone:string;email:string;address:string;slogan:string;primaryColor:string;secondaryColor:string;accentColor:string;itbisEnabled:boolean;itbisRate:number;logoUrl:string;coverImages:string[]};
const fallback:CompanyForm={name:"EILEN Electric Service",rnc:"1-31-00000-1",phone:"809-555-0147",email:"propuestas@eilen.do",address:"Santiago, República Dominicana",slogan:"Ingeniería que transforma energía",primaryColor:"#0F4C5C",secondaryColor:"#2F7D32",accentColor:"#F2A900",itbisEnabled:true,itbisRate:.18,logoUrl:"",coverImages:[]};
export function CompanyProfileForm(){
  const [form,setForm]=useState(fallback),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{fetch("/api/company").then(r=>r.ok?r.json():null).then(data=>{if(data)setForm({...fallback,...data,itbisRate:data.itbisRate == null ? 0.18 : Number(data.itbisRate),coverImages:Array.isArray(data.coverImages)?data.coverImages:[]})}).catch(()=>undefined)},[]);
  function set<K extends keyof CompanyForm>(key:K,value:CompanyForm[K]){setForm(old=>({...old,[key]:value}));}
  function imageToDataUrl(file:File,done:(value:string)=>void){const reader=new FileReader();reader.onload=()=>done(String(reader.result));reader.readAsDataURL(file);}
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/company",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setBusy(false);setMessage(response.ok?"Perfil y reglas fiscales guardados.":"No se pudo guardar. Inicia sesión con una cuenta administradora.");}
  return <form onSubmit={save} className="grid gap-6 lg:grid-cols-[1fr_.7fr]">
    <Card><CardHeader><CardTitle>Datos comerciales</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{(["name","rnc","phone","email","address","slogan"] as const).map((key,i)=><label key={key} className={i>3?"sm:col-span-2":""}><span className="label">{{name:"Nombre",rnc:"RNC",phone:"Teléfono",email:"Email",address:"Dirección",slogan:"Eslogan"}[key]}</span><input className="field" value={form[key]} onChange={e=>set(key,e.target.value)}/></label>)}</CardContent></Card>
    <div className="space-y-6"><Card><CardHeader><CardTitle>Identidad visual</CardTitle></CardHeader><CardContent className="space-y-4">{(["primaryColor","secondaryColor","accentColor"] as const).map((key)=><label key={key} className="flex items-center justify-between gap-4"><span className="text-sm font-medium">{{primaryColor:"Primario",secondaryColor:"Secundario",accentColor:"Acento"}[key]}</span><span className="flex items-center gap-2"><input type="color" value={form[key]} onChange={e=>set(key,e.target.value)}/><input className="field w-28" value={form[key]} onChange={e=>set(key,e.target.value)}/></span></label>)}<label className="flex h-24 cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed text-sm font-semibold text-slate-500 hover:bg-slate-50"><ImagePlus size={18}/>{form.logoUrl?"Cambiar logo":"Cargar logo"}<input type="file" className="hidden" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)imageToDataUrl(file,value=>set("logoUrl",value))}}/></label></CardContent></Card>
      <Card><CardHeader><CardTitle>ITBIS y fiscalización</CardTitle></CardHeader><CardContent className="space-y-4"><label className="flex items-center justify-between gap-4"><span className="text-sm font-medium">Aplicar ITBIS</span><input type="checkbox" checked={form.itbisEnabled} onChange={e=>set("itbisEnabled",e.target.checked)} className="h-4 w-4"/></label><label><span className="label">Tasa ITBIS (%)</span><input className="field" type="number" min="0" max="100" step="0.01" value={form.itbisRate*100} onChange={e=>set("itbisRate",Number(e.target.value)/100)}/></label></CardContent></Card>
      <Card><CardHeader><CardTitle>Biblioteca de portadas</CardTitle></CardHeader><CardContent><label className="flex h-28 cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed text-sm font-semibold text-slate-500 hover:bg-slate-50"><ImagePlus size={18}/>Agregar fotos aéreas o de proyectos<input type="file" multiple className="hidden" accept="image/*" onChange={e=>Array.from(e.target.files||[]).forEach(file=>imageToDataUrl(file,value=>setForm(old=>({...old,coverImages:[...old.coverImages,value]}))))}/></label>{form.coverImages.length>0&&<p className="mt-2 text-xs text-slate-500">{form.coverImages.length} imágenes guardadas en la biblioteca.</p>}</CardContent></Card>
      {message&&<p className="text-sm font-medium text-primary">{message}</p>}<Button className="w-full" disabled={busy}>{busy?<Loader2 className="animate-spin" size={17}/>:<Save size={17}/>}Guardar perfil</Button>
    </div>
  </form>;
}
