"use client";
import { useEffect,useState } from "react";
import { Building2,Loader2,Plus,Power,RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";

type Tenant={id:string;name:string;slug:string;rnc?:string|null;email?:string|null;active:boolean;_count:{users:number;customers:number;proposals:number}};
export function SuperAdminPanel(){
  const [tenants,setTenants]=useState<Tenant[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  async function load(){setLoading(true);const response=await fetch("/api/companies");if(response.ok)setTenants(await response.json());else setMessage("Esta sección requiere una sesión SuperAdmin.");setLoading(false)}
  useEffect(()=>{load()},[]);
  async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries());const response=await fetch("/api/companies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setSaving(false);if(!response.ok){setMessage(data.error||"No se pudo crear la empresa.");return;}e.currentTarget.reset();setMessage("Empresa y administrador creados correctamente.");await load()}
  async function toggle(tenant:Tenant){setMessage("");const response=await fetch("/api/companies",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:tenant.id,active:!tenant.active})});const data=await response.json();if(!response.ok){setMessage(data.error||"No se pudo cambiar el estado de la empresa.");return;}setMessage(`${tenant.name} quedó ${data.active?"activa":"inactiva"}.`);await load()}
  return <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle>Nueva empresa</CardTitle></CardHeader><CardContent><form onSubmit={create} className="space-y-4">{[["name","Nombre comercial","text"],["slug","Identificador (slug)","text"],["rnc","RNC","text"],["email","Email comercial","email"],["phone","Teléfono comercial","tel"],["adminName","Nombre del administrador","text"],["adminEmail","Correo del administrador","email"],["adminPassword","Contraseña temporal","password"]].map(([name,label,type])=><label key={name} className="block"><span className="label">{label}</span><input className="field" name={name} type={type} required={!['rnc','email','phone'].includes(name)} minLength={name==='adminPassword'?8:undefined}/></label>)}{message&&<p className="text-sm font-medium text-primary">{message}</p>}<Button className="w-full" disabled={saving}>{saving?<Loader2 size={17} className="animate-spin"/>:<Plus size={17}/>}Crear cuenta empresarial</Button></form></CardContent></Card><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Tenants registrados</CardTitle><button onClick={load} className="text-slate-500 hover:text-primary" aria-label="Actualizar"><RefreshCw size={17}/></button></CardHeader><CardContent>{loading?<div className="grid place-items-center py-16"><Loader2 className="animate-spin text-primary"/></div>:tenants.length===0?<p className="py-16 text-center text-sm text-slate-500">No hay empresas registradas.</p>:tenants.map(tenant=><div key={tenant.id} className="flex items-center gap-4 border-b py-4 last:border-0"><div className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary"><Building2 size={19}/></div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{tenant.name}</p><p className="text-xs text-slate-500">{tenant.slug} · {tenant.rnc||"Sin RNC"}</p></div><div className="hidden text-right text-xs text-slate-500 sm:block"><p>{tenant._count.users} usuarios</p><p>{tenant._count.proposals} propuestas</p></div><span className={tenant.active?"rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700":"rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600"}>{tenant.active?"Activo":"Inactivo"}</span><Button type="button" variant="outline" className="h-8 px-2" onClick={()=>void toggle(tenant)} title={tenant.active?"Desactivar empresa":"Activar empresa"}><Power size={15}/><span className="sr-only">{tenant.active?"Desactivar":"Activar"}</span></Button></div>)}</CardContent></Card></div>;
}
