import { apiHandler } from "@/lib/api-handler";
import { z } from "zod";
import { persistBodyMedia, readJson } from "@/lib/api-validation";
import { NextRequest,NextResponse } from "next/server";
import { sessionFromRequest } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
async function handleGET(request:NextRequest){const session=await sessionFromRequest(request);if(!session?.companyId)return NextResponse.json({error:"No autorizado"},{status:401});return NextResponse.json(await prisma.company.findUnique({where:{id:session.companyId}}));}
async function handlePATCH(request:NextRequest){const session=await sessionFromRequest(request);if(!session?.companyId||!["SUPERADMIN","COMPANY_ADMIN"].includes(session.role))return NextResponse.json({error:"No autorizado"},{status:403});const body=await persistBodyMedia(z.object({name:z.string().min(1).max(300).optional(),rnc:z.string().max(100).nullable().optional(),address:z.string().max(1000).nullable().optional(),phone:z.string().max(100).nullable().optional(),email:z.string().max(300).nullable().optional(),website:z.string().max(300).nullable().optional(),slogan:z.string().max(1000).nullable().optional(),logoUrl:z.string().max(5600000).nullable().optional(),coverImageUrl:z.string().max(5600000).nullable().optional(),backCoverImageUrl:z.string().max(5600000).nullable().optional(),primaryColor:z.string().regex(/^#[a-fA-F0-9]{6}$/).optional(),secondaryColor:z.string().regex(/^#[a-fA-F0-9]{6}$/).optional(),accentColor:z.string().regex(/^#[a-fA-F0-9]{6}$/).optional(),itbisEnabled:z.boolean().optional(),itbisRate:z.coerce.number().min(0).max(1).optional(),coverImages:z.array(z.string().max(5600000)).max(12).optional(),proposalValidityDays:z.coerce.number().int().min(1).max(365).optional()}).parse(await readJson(request)),session.companyId);const allowed={name:body.name,rnc:body.rnc,address:body.address,phone:body.phone,email:body.email,website:body.website,slogan:body.slogan,logoUrl:body.logoUrl,coverImageUrl:body.coverImageUrl,backCoverImageUrl:body.backCoverImageUrl,primaryColor:body.primaryColor,secondaryColor:body.secondaryColor,accentColor:body.accentColor,itbisEnabled:body.itbisEnabled,itbisRate:body.itbisRate,coverImages:body.coverImages,proposalValidityDays:body.proposalValidityDays};return NextResponse.json(await prisma.company.update({where:{id:session.companyId},data:allowed}));}

export const GET = apiHandler(handleGET);
export const PATCH = apiHandler(handlePATCH);
