import { ArrowUpRight, CircleDollarSign, FileCheck2, PanelsTopLeft, Plus } from "lucide-react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function DashboardPage() {
  const metrics = [["Propuestas este mes", "12", FileCheck2], ["Capacidad cotizada", "184.6 kWp", PanelsTopLeft], ["Valor en pipeline", "US$ 176,420", CircleDollarSign]] as const;
  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Panel comercial</p><h1 className="text-3xl font-black tracking-tight">Resumen</h1><p className="mt-1 text-sm text-slate-500">Actividad de propuestas y rendimiento del portafolio.</p></div><Link href="/dashboard/calculator" className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-white"><Plus size={17}/>Nueva propuesta</Link></div>
    <div className="grid gap-4 md:grid-cols-3">{metrics.map(([label,value,Icon]) => <Card key={label}><CardContent className="flex items-center justify-between"><div><p className="metric-value">{value}</p><p className="metric-label">{label}</p></div><div className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon size={22}/></div></CardContent></Card>)}</div>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><Card><CardHeader><CardTitle>Propuestas recientes</CardTitle></CardHeader><CardContent className="space-y-1">{[["PROP-2026-012","Grupo Herrera","24.8 kWp","US$ 25,510"],["PROP-2026-011","Residencial Valdez","12.4 kWp","US$ 13,080"],["PROP-2026-010","Almacenes Norte","48.3 kWp","US$ 45,900"]].map((row,i)=><div key={row[0]} className="grid grid-cols-[1fr_1.4fr_.8fr_1fr_auto] items-center gap-3 border-b py-3 text-sm last:border-0"><span className="font-semibold">{row[0]}</span><span>{row[1]}</span><span className="text-slate-500">{row[2]}</span><span className="text-right font-semibold">{row[3]}</span><span className={i===0?"rounded-full bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700":"rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700"}>{i===0?"Borrador":"Enviada"}</span></div>)}</CardContent></Card><Card className="bg-slate-950 text-white"><CardContent className="flex h-full flex-col justify-between p-6"><div><p className="text-sm font-semibold text-amber-400">Tasa de conversión</p><p className="mt-2 text-5xl font-black">41.7%</p><p className="mt-3 text-sm leading-6 text-slate-400">5 de 12 propuestas fueron aceptadas este mes.</p></div><div className="mt-8 flex items-center gap-2 text-sm font-semibold text-emerald-400"><ArrowUpRight size={18}/>8.4% vs. mes anterior</div></CardContent></Card></div>
  </div>;
}
